### ISSUE TITLE
Move from XMLHttpRequest() to fetch() ?

### ISSUE THREAD

**Issue by pwFoo** [edwinm/miq#1]
First of all... great work! Looks good and really small! 👍 

Maybe You could move to fetch() in $.ajax()? Modern browsers support it?

**Comment by pwFoo** [comment]
It returns to my mind that fetch() needs less code to do an ajax call, but I haven't get it done to populate php $_POST without a helper function to convert the body part to FormData...
With the helper function the code could be more then a simple XMLHttpRequest?

**Comment by edwinm** [comment]
Thanks!

In modern browsers, fetch is preferable above XMLHttpRequest.

But IE11 is still a supported browser who doesn't support fetch. So, the current version of miq still has to use  plan old XMLHttpRequest.
