### ISSUE TITLE
Handle simple selectors not with querySelectorAll?

### ISSUE THREAD

**Issue by pwFoo** [edwinm/miq#2]
Looks like You handle all selectors with querySelectorAll()? 
Simple selectors should be redirected to faster methods like getElementById, getElementsByClassName and getElementsByTagName to improve the performance.

**Comment by edwinm** [comment]
Whether querySelectorAll takes 1 or 10 microseconds does not make any difference to the user.

This is called a micro optimalization and is not worth any effort.
