### ISSUE TITLE
jQuery compatibility?

### ISSUE THREAD

**Issue by pwFoo** [edwinm/miq#3]
Is miq compatible with the correspond jQuery methods like https://github.com/kenwheeler/cash? Or act it just similiar?
Would be interesting because of jQuery plugin compatibility to miq ;)

**Comment by edwinm** [comment]
Miq supports a smell subset of jQuery. Miq does not support functions that can be accomplished in an other (easy) way. For example width and height can be retreived from getBoundingClientRect(), so a special jQuery-like function is not really neccessary. In this regard, Cash differs from Miq. Cash supports more functions and is also bigger.

When using only the functions miq provides and Cash supports, it should be possible to write a plugin that works in miq, cash and jQuery itself.

**Comment by pwFoo** [comment]
I played with KI.js with ist also a minimal jQuery like library, but just with size in mind. Some method weren't compatible. That's what I mean.

I don't think I need all the jQuery or Cash functions. The small set of functions available with miq looks good to me, but the result could differ between jQuery / Cash / ZeptoJS / ... and miq.

I'll do some tests with some (simple) jQuery plugins.

Thanks for sharing miq!
