### ISSUE TITLE
Modular build with plugins and a minimal core?

### ISSUE THREAD

**Issue by pwFoo** [edwinm/miq#4]
Is it possible to change miq to a modular build or a even smaller core extended by plugins?

Maybe it's possible to build a autoload / plugin include to keep it easy?
Found an (not tested by me and old) autoload.js gist.
https://gist.github.com/hassox/291054

I don't know if it would be possible to autoload the plugin if the method is called and not defined / loaded yet?

So just (small) core could be included and additional features autoloaded / included as needed?

**Comment by edwinm** [comment]
Interesting idea.

One of the important features of miq is its file size. And adding autoload functionality would increase the file size significantly. I also think the use case for autoload is really small. Building a JavaScript file with all needed functionality up front will give the best performance most of the time.
